apiVersion: v1
kind: ConfigMap
metadata: { name: parts-config }
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/partsdb
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/parts-store
