apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.postgres.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
