spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/partsdb
    username: parts
    password: parts
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/parts-store
