spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storedb
    username: store
    password: store
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

app:
  security:
    issuer-uri: http://localhost:8081/realms/computer-store
