spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: store
    password: store
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/computer-parts
server:
  port: 8080
logging:
  level:
    root: INFO
